// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBafwU3sGBR8_krReSjs0MS9CCSHnF-WvI',
    appId: '1:678486231444:web:c5fda3fe9642efbc74a781',
    messagingSenderId: '678486231444',
    projectId: 'fundpec-90090',
    authDomain: 'fundpec-90090.firebaseapp.com',
    storageBucket: 'fundpec-90090.appspot.com',
    measurementId: 'G-LH6S75XD5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD1ABeILltWT7av6Jr9fN0o0urLukSILA',
    appId: '1:678486231444:android:1cf96b8975a5ac5874a781',
    messagingSenderId: '678486231444',
    projectId: 'fundpec-90090',
    storageBucket: 'fundpec-90090.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCBjoCypLCup58KYpyDyhudC7gd6gdyRs',
    appId: '1:678486231444:ios:6d1485597dda6dcd74a781',
    messagingSenderId: '678486231444',
    projectId: 'fundpec-90090',
    storageBucket: 'fundpec-90090.appspot.com',
    iosBundleId: 'com.example.fundpec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCBjoCypLCup58KYpyDyhudC7gd6gdyRs',
    appId: '1:678486231444:ios:6d1485597dda6dcd74a781',
    messagingSenderId: '678486231444',
    projectId: 'fundpec-90090',
    storageBucket: 'fundpec-90090.appspot.com',
    iosBundleId: 'com.example.fundpec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBafwU3sGBR8_krReSjs0MS9CCSHnF-WvI',
    appId: '1:678486231444:web:b75bbf65ce53079474a781',
    messagingSenderId: '678486231444',
    projectId: 'fundpec-90090',
    authDomain: 'fundpec-90090.firebaseapp.com',
    storageBucket: 'fundpec-90090.appspot.com',
    measurementId: 'G-6EZ6L4HHWM',
  );
}
